module.exports = {
	GPI_LIST: [
		{ id: '01', label: 'GPI 1' },
		{ id: '02', label: 'GPI 2' },
		{ id: '03', label: 'GPI 3' },
		{ id: '04', label: 'GPI 4' },
		{ id: '05', label: 'GPI 5' },
		{ id: '06', label: 'GPI 6' },
		{ id: '07', label: 'GPI 7' },
		{ id: '08', label: 'GPI 8' },
		{ id: '09', label: 'GPI 9' },
		{ id: '10', label: 'GPI 10' },
		{ id: '11', label: 'GPI 11' },
		{ id: '12', label: 'GPI 12' },
		{ id: '13', label: 'GPI 13' },
		{ id: '14', label: 'GPI 14' },
		{ id: '15', label: 'GPI 15' },
		{ id: '16', label: 'GPI 16' }
	],
	GPO_LIST: [
		{ id: '01', label: 'GPO 1' },
		{ id: '02', label: 'GPO 2' },
		{ id: '03', label: 'GPO 3' },
		{ id: '04', label: 'GPO 4' },
		{ id: '05', label: 'GPO 5' },
		{ id: '06', label: 'GPO 6' },
		{ id: '07', label: 'GPO 7' },
		{ id: '08', label: 'GPO 8' },
		{ id: '09', label: 'GPO 9' },
		{ id: '10', label: 'GPO 10' },
		{ id: '11', label: 'GPO 11' },
		{ id: '12', label: 'GPO 12' },
		{ id: '13', label: 'GPO 13' },
		{ id: '14', label: 'GPO 14' },
		{ id: '15', label: 'GPO 15' },
		{ id: '16', label: 'GPO 16' }
	],
	MEM_LIST: [
		{ id: '01', label: 'MEM 1' },
		{ id: '02', label: 'MEM 2' },
		{ id: '03', label: 'MEM 3' },
		{ id: '04', label: 'MEM 4' },
		{ id: '05', label: 'MEM 5' },
		{ id: '06', label: 'MEM 6' },
		{ id: '07', label: 'MEM 7' },
		{ id: '08', label: 'MEM 8' },
		{ id: '09', label: 'MEM 9' },
		{ id: '10', label: 'MEM 10' },
		{ id: '11', label: 'MEM 11' },
		{ id: '12', label: 'MEM 12' },
		{ id: '13', label: 'MEM 13' },
		{ id: '14', label: 'MEM 14' },
		{ id: '15', label: 'MEM 15' },
		{ id: '16', label: 'MEM 16' }
	],
	KEY_LIST: [
		{ id: '01', label: 'KEY 1' },
		{ id: '02', label: 'KEY 2' },
		{ id: '03', label: 'KEY 3' },
		{ id: '04', label: 'KEY 4' },
		{ id: '05', label: 'KEY 5' },
		{ id: '06', label: 'KEY 6' },
		{ id: '07', label: 'KEY 7' },
		{ id: '08', label: 'KEY 8' },
		{ id: '09', label: 'KEY 9' },
		{ id: '10', label: 'KEY 10' },
		{ id: '11', label: 'KEY 11' },
		{ id: '12', label: 'KEY 12' },
		{ id: '13', label: 'KEY 13' },
		{ id: '14', label: 'KEY 14' },
		{ id: '15', label: 'KEY 15' },
		{ id: '16', label: 'KEY 16' }
	],
	COLORS: [
		//the colors are the same between the two different types of panels, but only the ones with a hex value are implemented as surface colors
		{ id: '00', label: 'SOLID_DARK', hex: '#000000' },
		{ id: '01', label: 'SOLID_RED', hex: '#FF0000' },
		{ id: '02', label: 'SOLID_GREEN', hex: '#00FF00' },
		{ id: '03', label: 'SOLID_AMBER', hex: '#FF8000' },
		{ id: '38', label: 'SOLID_AQUA', hex: '#00FFFF' },
		{ id: '20', label: 'SOLID_BLUE', hex: '#0000FF' },
		{ id: '32', label: 'SOLID_PURPLE', hex: '#FF00FF' },
		{ id: '26', label: 'SOLID_WHITE', hex: '#FFFFFF' },
		{ id: '04', label: 'BLINKING_RED_FAST' },
		{ id: '05', label: 'BLINKING_RED_SLOW' },
		{ id: '06', label: 'BLINKING_GREEN_FAST' },
		{ id: '07', label: 'BLINKING_GREEN_SLOW' },
		{ id: '08', label: 'BLINKING_AMBER_FAST' },
		{ id: '09', label: 'BLINKING_AMBER_SLOW' },
		{ id: '39', label: 'BLINKING_AQUA_FAST' },
		{ id: '40', label: 'BLINKING_AQUA_SLOW' },
		{ id: '21', label: 'BLINKING_BLUE_FAST' },
		{ id: '22', label: 'BLINKING_BLUE_SLOW' },
		{ id: '33', label: 'BLINKING_PURPLE_FAST' },
		{ id: '34', label: 'BLINKING_PURPLE_SLOW' },
		{ id: '27', label: 'BLINKING_WHITE_FAST' },
		{ id: '28', label: 'BLINKING_WHITE_SLOW' },
		{ id: '10', label: 'SOLID_RED_DIM' },
		{ id: '11', label: 'SOLID_GREEN_DIM' },
		{ id: '12', label: 'SOLID_AMBER_DIM' },
		{ id: '41', label: 'SOLID_AQUA_DIM' },
		{ id: '23', label: 'SOLID_BLUE_DIM' },
		{ id: '35', label: 'SOLID_PURPLE_DIM' },
		{ id: '29', label: 'SOLID_WHITE_DIM' },
		{ id: '13', label: 'BLINKING_RED_FAST_DIM' },
		{ id: '14', label: 'BLINKING_RED_SLOW_DIM' },
		{ id: '15', label: 'BLINKING_GREEN_FAST_DIM' },
		{ id: '16', label: 'BLINKING_GREEN_SLOW_DIM' },
		{ id: '17', label: 'BLINKING_AMBER_FAST_DIM' },
		{ id: '18', label: 'BLINKING_AMBER_SLOW_DIM' },
		{ id: '42', label: 'BLINKING_AQUA_FAST_DIM' },
		{ id: '43', label: 'BLINKING_AQUA_SLOW_DIM' },
		{ id: '24', label: 'BLINKING_BLUE_FAST_DIM' },
		{ id: '25', label: 'BLINKING_BLUE_SLOW_DIM' },
		{ id: '36', label: 'BLINKING_PURPLE_FAST_DIM' },
		{ id: '37', label: 'BLINKING_PURPLE_SLOW_DIM' },
		{ id: '30', label: 'BLINKING_WHITE_FAST_DIM' },
		{ id: '31', label: 'BLINKING_WHITE_SLOW_DIM' }		
	]
}